import "./styles/uniList.css"
import { useState } from 'react' 


 const universities = [
  "The University of Aberdeen",
  "Abertay University",
  "Aberystwyth University",
  "AECC University College",
  "Anglia Ruskin University",
  "Aston University",
  "Bangor University",
  "Bath Spa University",
  "The University of Bath",
  "University of Bedfordshire",
  "Queen's University Belfast",
  "Birkbeck College",
  "Birmingham City University",
  "The University of Birmingham",
  "University College Birmingham",
  "Birmingham Newman University",
  "Bishop Grosseteste University",
  "The University of Bolton",
  "The Arts University Bournemouth",
  "Bournemouth University",
  "The University of Bradford",
  "The University of Brighton",
  "The University College of Osteopathy",
  "The University of Bristol",
  "Brunel University London",
  "Buckinghamshire New University",
  "The University of Cambridge",
  "The Institute of Cancer Research",
  "Canterbury Christ Church University",
  "Cardiff University",
  "Cardiff Metropolitan University",
  "The University of Central Lancashire",
  "University of Chester",
  "The University of Chichester",
  "City, University of London",
  "Conservatoire for Dance and Drama",
  "Courtauld Institute of Art",
  "Coventry University",
  "Cranfield University",
  "University for the Creative Arts",
  "University of Cumbria",
  "De Montfort University",
  "University of Derby",
  "The University of Dundee",
  "University of Durham",
  "The University of East Anglia",
  "The University of East London",
  "Edge Hill University",
  "Edinburgh Napier University",
  "The University of Edinburgh",
  "The University of Essex",
  "The University of Exeter",
  "Falmouth University",
  "The National Film and Television School",
  "Glasgow Caledonian University",
  "Glasgow School of Art",
  "The University of Glasgow",
  "University of Gloucestershire",
  "Goldsmiths College",
  "The University of Greenwich",
  "Guildhall School of Music and Drama",
  "Harper Adams University",
  "Heriot-Watt University",
  "University of Hertfordshire",
  "The University of Huddersfield",
  "The University of Hull",
  "Imperial College of Science, Technology and Medicine",
  "Keele University",
  "The University of Kent",
  "King's College London",
  "Kingston University",
  "The University of Lancaster",
  "Leeds Arts University",
  "Leeds Beckett University",
  "The University of Leeds",
  "Leeds Trinity University",
  "The University of Leicester",
  "The University of Lincoln",
  "Liverpool Hope University",
  "Liverpool John Moores University",
  "The Liverpool Institute for Performing Arts",
  "The University of Liverpool",
  "Liverpool School of Tropical Medicine",
  "University of the Arts, London",
  "London Business School",
  "University of London (Institutes and activities)",
  "London Metropolitan University",
  "London South Bank University",
  "London School of Economics and Political Science",
  "London School of Hygiene and Tropical Medicine",
  "Loughborough University",
  "The Manchester Metropolitan University",
  "The University of Manchester",
  "Middlesex University",
  "Newcastle University",
  "The University of Northampton",
  "University of Northumbria at Newcastle",
  "Norwich University of the Arts",
  "University of Nottingham",
  "The Nottingham Trent University",
  "The Open University",
  "Oxford Brookes University",
  "The University of Oxford",
  "Arts University Plymouth",
  "University of Plymouth",
  "The University of Portsmouth",
  "Queen Margaret University, Edinburgh",
  "Queen Mary University of London",
  "Ravensbourne University London",
  "The University of Reading",
  "Robert Gordon University",
  "Roehampton University",
  "Rose Bruford College of Theatre and Performance",
  "Royal Academy of Music",
  "Royal Agricultural University",
  "Royal College of Art",
  "Royal College of Music",
  "The Royal Central School of Speech and Drama",
  "Royal Holloway and Bedford New College",
  "Royal Northern College of Music",
  "The Royal Veterinary College",
  "The University of St. Andrews",
  "St George's, University of London",
  "St Mary's University College",
  "St Mary's University, Twickenham",
  "The University of Salford",
  "SOAS University of London",
  "SRUC",
  "Sheffield Hallam University",
  "The University of Sheffield",
  "Solent University",
  "The University of Southampton",
  "Staffordshire University",
  "The University of Stirling",
  "University of St Mark and St John",
  "Stranmillis University College",
  "The University of Strathclyde",
  "University of Suffolk",
  "The University of Sunderland",
  "The University of Surrey",
  "The University of Sussex",
  "Swansea University",
  "Teesside University",
  "Trinity Laban Conservatoire of Music and Dance",
  "University of Wales Trinity Saint David",
  "University of the Highlands and Islands",
  "Ulster University",
  "University College London",
  "University of South Wales",
  "The University of Warwick",
  "University of the West of England, Bristol",
  "The University of the West of Scotland",
  "The University of West London",
  "The University of Westminster",
  "The University of Winchester",
  "The University of Wolverhampton",
  "University of Worcester",
  "Wrexham University",
  "Writtle University College",
  "York St John University",
  "The University of York"
];

// function that generates the university list to be chosen, and creates the search function to choose universities
export default function UniListSearch( { wantedUniversities, setWantedUniversities }) {
  const [characters, setCharacters] = useState("")
  // console.log(wantedUniversities)

  return (
    <div>
      <input type="text" id="myInput"  placeholder="Search for names.." onChange={(e) => setCharacters(e.target.value)}></input>

      <div id="listofUnisBox">
      <ul id='myUL' placeholder = 'Search for names... '>
        {universities.filter(university => university.includes(characters)).map((university, index) => <li key={index} onClick={() => { if (wantedUniversities.includes(university) === false) {setWantedUniversities([...wantedUniversities, university]);}}  } >{university}</li>)}
      </ul>
      </div>

      <div id="listContainer">
      {wantedUniversities.map(uni =><div className="removeUniversities" key={uni}>{uni}<button class ="removeUniversitiesButton" onClick = {() => setWantedUniversities(wantedUniversities.filter(uniName => uniName !== uni))}>X</button> </div> )}
      </div>

      <button onClick={() => setWantedUniversities([])} >Clear All</button>
      <button onClick={() => setWantedUniversities(universities)}>Select All</button>
    </div>
  )

}   